In [1]:
import glob
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option("display.max_colwidth", 100)

## Data Dictionary

In [2]:
#Import data dictionary for contributions data. Clean up column names and drop last row which isn't a column.
names = ["Type", "Name", "Description"]
data_dict = pd.read_csv("data/Contribution_Key_9-3-15.csv", usecols=names)
data_dict.columns = data_dict.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
data_dict = data_dict.drop(data_dict.index[-1])
data_dict

,type,name,description
0,Character,ELECTION,Election Cycle
1,Character,OFFICECD,Office Sought: [1=Mayor; 2=Public Advocate; 3=Comptroller; 4=Borough President; 5=City Council; ...
2,Character,RECIPID,"Candidate ID, assigned by the CFB"
3,Character,CANCLASS,"Campaign Finance Program Classification: [Participant, Non-Participant, Limited Participant, Und..."
4,Character,RECIPNAME,Candidate's Last Name
5,Character,COMMITTEE,"Committee ID, assigned by the CFB"
6,Numeric,FILING,Disclosure Statement Filing Period
7,Character,SCHEDULE,Schedule: [ABC=Monetary Contributions; D=In-Kind Contributions; G=Transfers In; K=Loans/Liabilit...
8,Numeric,PAGENO,Page Number of schedule on which information was reported (paper filings only)
9,Numeric,SEQUENCENO,Sequence Number on page of schedule on which information was reported (paper filings only)
10,Character,REFNO,Transaction Reference Number
11,Date,DATE,Date Received
12,Date,REFUNDDATE,Date of Refund/Loan forgiven
13,Character,NAME,Contributor's Name
14,Character,C_CODE,Contributor Type: [CAN=Candidate; CORP=Corporation; EMPO=Labor Union; FAM=Candidate's Family; IN...
15,Character,STRNO,"Contributor's Street Number - If C_CODE = IND, CAN, FAM or SPO, Then field = Blank"
16,Character,STRNAME,"Contributor's Street Name - If C_CODE = IND, CAN, FAM or SPO, Then field = Blank"
17,Character,APARTMENT,"Contributor's Apartment Number - If C_CODE = IND, CAN, FAM or SPO, Then field = Blank"
18,Character,BOROUGHCD,Contributor's Borough Code: [K=Brooklyn; M=Manhattan; Q=Queens; S=Staten Island; X=Bronx; Z=Outs...
19,Character,CITY,"Contributor's City, Schedule N - Vendor's City"
20,Character,STATE,"Contributor's State, Schedule N - Vendor's State"
21,Character,ZIP,Contributor's Zip Code
22,Character,OCCUPATION,Contributor's Occupation
23,Character,EMPNAME,Contributor's Employer
24,Character,EMPSTRNO,Contributor's Employer's Street Number
25,Character,EMPSTRNAME,Contributor's Employer's Street Name
26,Character,EMPCITY,Contributor's Employer's City
27,Character,EMPSTATE,Contributor's Employer's State
28,Numeric,AMNT,Amount
29,Numeric,MATCHAMNT,Matchable Amount of Contribution
30,Numeric,PREVAMNT,Total of Previous Contributions
31,Numeric,PAY_METHOD,Method of Payment: [0=Unknown; 1=Cash; 2=Check; 3=Other; 4=Credit Card; 5=Money Order]
32,Character,INTERMNO,"Intermediary Number, assigned by candidate"
33,Character,INTERMNAME,Intermediary's Name (if any)
34,Character,INTSTRNO,"Intermediary's Street Number, assigned by candidate \rIf C_CODE = IND, CAN, FAM or SPO, Then fie..."
35,Character,INTSTRNM,"Intermediary's Street Name \rIf C_CODE = IND, CAN, FAM or SPO, Then field = Blank"
36,Character,INTAPTNO,"Intermediary's Apartment Number \rIf C_CODE = IND, CAN, FAM or SPO, Then field = Blank"
37,Character,INTCITY,Intermediary's City
38,Character,INTST,Intermediary's State
39,Character,INTZIP,Intermediary's Zip Code
40,Character,INTEMPNAME,Intermediary's Employer Name
41,Character,INTEMPSTNO,Intermediary's Employer Street Number
42,Character,INTEMPSTNM,Intermediary's Employer Street Name
43,Character,INTEMPCITY,Intermediary's Employer City
44,Character,INTEMPST,Intermediary's Employer State
45,Character,INTOCCUPA,Intermediary's Occupation
46,Character,PURPOSECD,Purpose Code (for Schedule D/In-Kind Contributions): [ADVAN=Advance Repayment; CMAIL=Campaign Ma...
47,Character,EXEMPTCD,Exempt Code: [C=Compliance Costs; E=Previous Election Costs; P=Petition Challenges; S=Constituen...
48,Character,ADJTYPECD,Schedule M /Adjustment Type Code: [0=Unknown; 1=Returned Check 2=Refund; 5=Other]
49,Character,RR-IND,Runoff/Rerun Indicator
50,Character,SEG-IND,Segregated Indicator
51,Character,INT_C_CODE,Intermediary's Name Code

## NYC Campaign Contributions data

In [3]:
#Import of 2009, 2013 and 2017 New York City Campaign Contributions. 
#Parse dates from following columns.

source = "https://www.nyccfb.info/follow-the-money/data-library/"

date_col = ["DATE", "REFUNDDATE"]

df = pd.concat([pd.read_csv(f, encoding="latin1", parse_dates=date_col, low_memory=False) \
                for f in glob.glob('data/*contribution.csv')], ignore_index = True)

df.shape

(466019, 52)

In [4]:
#change column names to be more pythonic
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
df.head(5)

,election,officecd,recipid,canclass,recipname,committee,filing,schedule,pageno,sequenceno,refno,date,refunddate,name,c_code,strno,strname,apartment,boroughcd,city,state,zip,occupation,empname,empstrno,empstrname,empcity,empstate,amnt,matchamnt,prevamnt,pay_method,intermno,intermname,intstrno,intstrnm,intaptno,intcity,intst,intzip,intempname,intempstno,intempstnm,intempcity,intempst,intoccupa,purposecd,exemptcd,adjtypecd,rr_ind,seg_ind,int_c_code
0,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,NaN,NaN,R0000020,2009-01-22,NaT,"Morris, Blake",IND,NaN,NaN,NaN,K,Brooklyn,NY,11226,Attorney,Self-employed,462,East 16th Street,Brooklyn,NY,100.0,100.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
1,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,NaN,NaN,R0000022,2009-02-03,NaT,"Pikttch, Ruth",IND,NaN,NaN,NaN,K,Brooklyn,NY,11214,Retired,NaN,2122,78th Street,Brooklyn,NY,50.0,50.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
2,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,NaN,NaN,R0000024,2009-01-22,NaT,"Goldstein, Benita",IND,NaN,NaN,NaN,M,New York,NY,10021,Office Manager,Mirrors by Jordan,38-27,28th Street,Long Island City,NY,40.0,40.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
3,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,NaN,NaN,R0000025,2008-11-06,NaT,"GOODWIN, GWEN",CAN,NaN,NaN,NaN,M,New York,NY,10029,Make-up Artist,Self-employed,152,East 100th Street,New York,NY,25.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
4,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,NaN,NaN,R0000035,2009-02-26,NaT,"Anderson, Peter",IND,NaN,NaN,NaN,M,New York,NY,10037,Letter Carrier,U.S. Postal Service,421,8th Avenue,New York,NY,40.0,40.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN

In [5]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466019 entries, 0 to 466018
Data columns (total 52 columns):
election      466019 non-null int64
officecd      466019 non-null object
recipid       466019 non-null object
canclass      465418 non-null object
recipname     466019 non-null object
committee     465418 non-null object
filing        466019 non-null object
schedule      466019 non-null object
pageno        0 non-null float64
sequenceno    0 non-null float64
refno         466019 non-null object
date          465705 non-null datetime64[ns]
refunddate    9524 non-null datetime64[ns]
name          466018 non-null object
c_code        466018 non-null object
strno         0 non-null float64
strname       0 non-null float64
apartment     0 non-null float64
boroughcd     462722 non-null object
city          463810 non-null object
state         463685 non-null object
zip           462717 non-null object
occupation    382649 non-null object
empname       340914 non-null object
empstrno      303720 non-null object
empstrname    307513 non-null object
empcity       307696 non-null object
empstate      307243 non-null object
amnt          466019 non-null float64
matchamnt     466019 non-null float64
prevamnt      466019 non-null float64
pay_method    466019 non-null int64
intermno      27848 non-null float64
intermname    27848 non-null object
intstrno      0 non-null float64
intstrnm      0 non-null float64
intaptno      0 non-null float64
intcity       27281 non-null object
intst         27261 non-null object
intzip        27196 non-null float64
intempname    24113 non-null object
intempstno    23470 non-null object
intempstnm    23546 non-null object
intempcity    23541 non-null object
intempst      23514 non-null object
intoccupa     25116 non-null object
purposecd     2759 non-null object
exemptcd      33 non-null object
adjtypecd     9534 non-null float64
rr_ind        465418 non-null object
seg_ind       462665 non-null object
int_c_code    27848 non-null object
dtypes: datetime64[ns](2), float64(14), int64(2), object(34)
memory usage: 836.9 MB

In [6]:
# Number of nulls by column
df.isnull().sum()

election           0
officecd           0
recipid            0
canclass         601
recipname          0
committee        601
filing             0
schedule           0
pageno        466019
sequenceno    466019
refno              0
date             314
refunddate    456495
name               1
c_code             1
strno         466019
strname       466019
apartment     466019
boroughcd       3297
city            2209
state           2334
zip             3302
occupation     83370
empname       125105
empstrno      162299
empstrname    158506
empcity       158323
empstate      158776
amnt               0
matchamnt          0
prevamnt           0
pay_method         0
intermno      438171
intermname    438171
intstrno      466019
intstrnm      466019
intaptno      466019
intcity       438738
intst         438758
intzip        438823
intempname    441906
intempstno    442549
intempstnm    442473
intempcity    442478
intempst      442505
intoccupa     440903
purposecd     463260
exemptcd      465986
adjtypecd     456485
rr_ind           601
seg_ind         3354
int_c_code    438171
dtype: int64

In [7]:
# Drop columns where majority of the data is null
df = df.dropna(axis=1, thresh=400000)
df.head(5)

,election,officecd,recipid,canclass,recipname,committee,filing,schedule,refno,date,name,c_code,boroughcd,city,state,zip,amnt,matchamnt,prevamnt,pay_method,rr_ind,seg_ind
0,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,R0000020,2009-01-22,"Morris, Blake",IND,K,Brooklyn,NY,11226,100.0,100.0,0.0,2,N,N
1,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,R0000022,2009-02-03,"Pikttch, Ruth",IND,K,Brooklyn,NY,11214,50.0,50.0,0.0,2,N,N
2,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,R0000024,2009-01-22,"Goldstein, Benita",IND,M,New York,NY,10021,40.0,40.0,0.0,2,N,N
3,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,R0000025,2008-11-06,"GOODWIN, GWEN",CAN,M,New York,NY,10029,25.0,0.0,0.0,1,N,N
4,2009,5,1009,P,"Goodwin, Gwen",H,7,ABC,R0000035,2009-02-26,"Anderson, Peter",IND,M,New York,NY,10037,40.0,40.0,0.0,2,N,N

In [8]:
#Set dtypes to category for the following columns, minimizing memory usage

catergory_cols = ["OFFICECD","CANCLASS","SCHEDULE","C_CODE", "BOROUGHCD","PAY_METHOD", "RR_IND", "SEG_IND"]

for cols in catergory_cols:
    df[cols] = df[cols].astype("category")

KeyError: 'OFFICECD'

In [ ]:
df.info(memory_usage="deep")

# Exploratory Data Analysis

Who is funding the candidates?